### ISSUE TITLE
TypeError: $parent.getChildren is not a function

### ISSUE THREAD

**Issue by johndoyle** [UltimateModuleCreator/umc#53]
Hi - looking to create simple module that has a Relation between two Entities.  I have created two simple Entities - Pet and Owner and wanted to link so that there are multiple pets to an owner defined.  

After creating the Entities and going to create a Relation (Add Entity Relation Button) I see the blank form added but the Entity 1 and Entity 2 dropdowns are blank and the JS console gives the error:  "TypeError: $parent.getChildren is not a function".  

I have tried on several Browsers with empty caches

**Comment by UltimateModuleCreator** [comment]
@johndoyle I just found the same issue a few hours ago. I don't want to explain how that happened because I'm ashamed of it :). You can do a `git pull`. the issue should be fixed in version 4.2.2. If for some reason that does not work just look for the file `relation.yml` and replace `$parent.getChildren('_entities')` with `$parent.children['_entities']`. There should be 2 places where that needs to be changed. Let me know if it works.

**Comment by johndoyle** [comment]
Thanks very much - all working now.  Don't feel ashamed easy mistake to make :-)
